### ISSUE TITLE
Allow use with BaseCommand

### ISSUE THREAD

**Issue by jayvdb** [daadu/django-admintool-command#5]
It would be nice to allow use with normal django commands.

https://github.com/willandskill/django-executor allows this, extracting the args & options from the arg parser.  See my PR there.

**Comment by jayvdb** [comment]
PR https://github.com/daadu/django-admintool-command/pull/6 only allows use with BaseCommand, it doesnt extract the args and options.

Also note even with that, it is incompatible with django-click due to https://github.com/GaretJax/django-click/issues/10

**Comment by daadu** [comment]
#6 PR has landed on `v0.1.1`. Hence, closing this issue.
